@:enum
abstract _CombatAction(String) {
  var ACTION_ATTACK = 'ACTION_ATTACK';
  var ACTION_CHARGE = 'ACTION_CHARGE';
  var ACTION_DRAW = 'ACTION_DRAW';
  var ACTION_DRINK = 'ACTION_DRINK';
  var ACTION_MOVE = 'ACTION_MOVE';
  var ACTION_PARRY = 'ACTION_PARRY';
  var ACTION_RETREAT = 'ACTION_RETREAT';
  var ACTION_SHOOT = 'ACTION_SHOOT';
  var ACTION_WAIT = 'ACTION_WAIT';
}
